@extends('frontend.layouts.app')

@section('content')
    <section class="page-section-big bg-white" id="about">
        <div class="container">
        <div class="row">
            <div class="col-lg-12 mx-auto text-justify">
                   <div class="entry-header">
                    <div class="container">
                        <h2 class="entry-title" itemprop="headline">Sejarah Berdirinya Jakarta Islamic Centre</h2>
                    </div>
                   </div>
                   <div class="container">
                    <div class="row">
                    <div class="col-md-9">
                            <main class="content" role="main" itemprop="mainContentOfPage">
                                    <article id="post-1626" class="post-1626 page type-page status-publish hentry" itemscope="itemscope"
                                    itemtype="http://schema.org/CreativeWork">
                                    <div class="entry-content" itemprop="text">
                                        <p><img class="aligncenter size-full wp-image-1690" src="http://islamic-center.or.id/wp-content/uploads/2014/01/master-plan.jpg" alt="master plan" width="100%" srcset="http://islamic-center.or.id/wp-content/uploads/2014/01/master-plan.jpg 893w, http://islamic-center.or.id/wp-content/uploads/2014/01/master-plan-300x229.jpg 300w" sizes="(max-width: 893px) 100vw, 893px" /></p>
                    <hr class="light my-4">
                    <p style="text-align: left;"><p>Pusat Pengkajian dan Pengembangan Islam Jakarta (Jakarta Islamic Centre) adalah sebuah lembaga yang berdiri di eks Lokasi Resosialisasi (Lokres) Kramat Tunggak, Tanjung Priuk,  Jakarta Utara.</p>
                    <p>Lokres Kramat Tunggak adalah nama sebuah Panti Sosial Karya Wanita (PKSW) Teratai Harapan Kramat Tunggak, yang terletak di jalan Kramat Jaya RW 019, Kelurahan Tugu Utara, Kecamatan Koja, Kotamadya Jakarta Utara. Areal tersebut tepatnya menempati lahan seluas 109.435 m<sup>2</sup> yang terdiri dari sembilan Rukun Tetangga (RT). Kramat Tunggak (kramtung), kemashurannya tidak saja terkenal di Indonesia, namun juga terkenal hingga ke seluruh Asia Tenggara sebagai pusat jajan terbesar bagi kaum hidung belang. Pada awal pembukaannya tahun 1970-an, terdapat 300 orang WTS dengan 76 orang germo. Jumlah ini terus bertambah seiring bertambah bulan dan tahun. Menjelang akhir ditutupnya Lokres Kramtung tahun 1999, jumlahnya mencapai 1.615 orang WTS di bawah asuhan 258 orang germo/mucikari. Mereka tinggal di 277 unit bangunan yang memiliki 3.546 kamar. Artinya, lokalisasi ini tumbuh dan berkembang dengan pesat yang akhirnya menimbulkan masalah baru pada masyarakat di lingkungan sekitarnya dan sekaligus citra Jakarta yang tidak bisa dipisahkan dari sejarahnya sebagai sebuah kultur Betawi yang sangat identik sebagai komunitas Islam yang terbuka, bersemangat multikultur, toleran dan sangat mencintai Islam sebagai identitas utama kebudayaan mereka.</p>
                    <p>Kondisi demikian ini menimbulkan desakan yang tidak henti-hentinya dari ulama dan masyarakat agar <b>P</b><b>anti </b><b>S</b><b>osial </b><b>K</b><b>arya </b><b>W</b><b>anita (</b><b>PKSW</b><b>)</b><b> T</b><b>eratai </b><b>H</b><b>arapan </b><b>K</b><b>ramat </b><b>T</b><b>unggak </b>ditutup<b>. </b>Adanya desakan yang semakin menguat tersebut pada akhirnya dilakukan penelitian oleh Dinas Sosial bersama Universitas Indonesia untuk tentang sejauhmana penolakan masyarakat terhadap PKSW Teratai Harapan Kramat Tunggak. Dari hasil penelitian tersebut, pada tahun 1997 direkomendasikan agar Lokres tersebut ditutup. Pada tahun 1998 dikeluarkan SK Gubernur KDKI Jakarta No. 495/1998 tentang penutupan panti sosial tersebut selambat-lambatnya akhir Desember 1999. Pada 31 Desember 1999, Lokres Kramat Tunggak secara resmi ditutup melalui SK Gubernur KDKI Jakarta No. 6485/1998. Selanjutnya Pemda Provinsi DKI Jakarta melakukan pembebasan lahan eks lokres Kramat Tunggak.</p>
                    <p>Setelah dibebaskan banyak muncul gagasan terhadap lokasi bekas Kramat Tunggak tersebut, ada yang mengusulkan pembangunan pusat perdagangan (mall), perkantoran dan lain sebagainya. Namun Gubernur H. Sutiyoso memiliki ide lain yaitu membangun Islamic Centre. Sebuah ide yang cemerlang yang menyatukan kelompok-kelompok lain yang awalnya berbeda-beda. Pada tahun 2001 Gubernur Sutiyoso melakukan sebuah Forum Curah Gagasan dengan seluruh elemen masyarakat untuk mengetahui sejauhmana dukungan masyarakat terhadap sebuah perubahan yang telah dicanangkan. Ternyata 24 Mei 2001 dukungan itu semakin menguat. Gagasan untuk membangun Jakarta Islamic Centre (JIC) dikemukakan Gubernur Sutiyoso kepada Prof. Azzumardi Azra (Rektor UIN Syarif Hidayatullah) di New York di sela-sela kunjungannya ke PBB pada tanggal 11-18 April 2001 dan mendapatkan respon yang sangat positif. Setelah adanya konsultasi terus menerus antara masyarakat, ulama, praktisi baik skala lokal maupun regional bahkan international akhirnya diwujudkan dalam sebuah master plan pembangunan JIC pada tahun 2002. Kemudian dalam rangka memperkuat ide dan gagasan pembangunan JIC,pada Agustus 2002 dilakukan Studi Komparasi ke Islamic Centre di Mesir, Iran, Inggris dan Perancis. Pada tahun yang sama, dilakukan perumusan Organisasi dan Manajemen JIC. Kehadiran JIC ternyata sesuatu yang sangat fenomenal sebagai produk zaman yang strategis dan monumental.</p>
                    <p>Dalam rangka menyongsong cita-cita besar umat Islam yang digantungkan kepada Jakarta Islamic Centre, dikeluarkan SK Gubernur KDKI No. 99/2003 tentang Pembentukan Organisasi dan Tata Kerja Badan Pengelola Pusat Pengkajian dan Pengembangan Islam Jakarta (Jakarta Islamic Centre). Selanjutnya pada tahun April 2004, Badan Pengelola Pusat Pengkajian dan Pengembangan Islam Jakarta (Jakarta Islamci Centre) diangkat/dilantik melalui SK Gubernur KDKI Jakarta No. 651/2004.</p>
                    <p>Namun selanjutnya, kehadiran JIC tidak sekedar hanya merubah tanah hitam menjadi putih, atau hanya sebuah masjid saja, melainkan lebih dari itu JIC diharapkan menjadi salah satu simpul pusat peradaban Islam di Indonesia dan Asia Tenggara yang menjadi simbol kebangkitan Islam di Asia dan Dunia. Ciri peradaban yang dimaksud adalah dengan adanya kelengkapan fasilitasi fungsi-fungsi kemakmuran masjid yang terdiri dari fungsi peribadatan, fungsi kediklatan dan fungsi pedagangan/bisnis.</p>
                </div>
            </div>
        </div>
    </section>
@endsection